name: seamless-m4t-v2-large
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.10.12
    - pip
    - pip:
        - torch
        - torchaudio
        - accelerate
        - protobuf
        - sentencepiece
        - transformers
